### ISSUE TITLE
Initial prototype

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-scale-to-zero#1]
The first version of this plugin will have configuration like this:

```yaml
plugins:
  datasette-scale-to-zero:
    duration: 5s
```

This will cause Datasette to quit if it has not had any traffic in the past 5s.
